const catalog=document.getElementById("catalog"),searchInput=document.getElementById("bookSearch"),resultCount=document.getElementById("resultCount"),emptyState=document.getElementById("emptyState"),themeToggle=document.getElementById("themeToggle"),themeIcon=themeToggle.querySelector(".theme-icon"),themeLabel=themeToggle.querySelector(".theme-label"),dialog=document.getElementById("bookDialog"),dialogCover=document.getElementById("dialogCover"),dialogTitle=document.getElementById("dialogTitle"),dialogMeta=document.getElementById("dialogMeta"),dialogDescription=document.getElementById("dialogDescription"),dialogClose=document.getElementById("dialogClose"),readerName=document.getElementById("readerName"),secretMode=document.getElementById("secretMode"),readButton=document.getElementById("readButton"),readerHint=document.getElementById("readerHint");
let activeBookId=null;
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function coverHtml(book){if(book.cover)return `<img class="book-cover-image" src="${book.cover}" alt="Capa de ${escapeHtml(book.title)}" loading="lazy">`;return `<div class="book-cover-placeholder" style="--placeholder:${book.accent||"#80677a"}"><span class="placeholder-top">CLUBE DO LIVRO</span><strong>${escapeHtml(book.title)}</strong><small>${escapeHtml(book.author)}</small><span class="placeholder-bottom">EDIÇÃO DO ACERVO</span></div>`}
function renderBooks(list){catalog.innerHTML=list.map(book=>`<article class="book-card" data-book-id="${book.id}" role="button" tabindex="0" aria-label="Abrir ${escapeHtml(book.title)}"><div class="book-number">${String(book.id).padStart(2,"0")}</div><div class="book-cover-frame">${coverHtml(book)}</div><div class="book-info"><p class="book-index">VOLUME ${String(book.id).padStart(2,"0")}</p><h2 class="book-title">${escapeHtml(book.title)}</h2><p class="book-meta"><span>${escapeHtml(book.author)}</span><span>· ${book.year}</span></p></div></article>`).join("");resultCount.textContent=`${list.length} ${list.length===1?"livro":"livros"} no acervo`;emptyState.hidden=list.length!==0;catalog.querySelectorAll(".book-card").forEach(card=>{const open=()=>openBook(Number(card.dataset.bookId));card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}})})}
function openBook(id){const book=books.find(x=>x.id===id);if(!book)return;activeBookId=id;dialogTitle.textContent=book.title;dialogMeta.textContent=`${book.author} · ${book.year}`;dialogDescription.textContent=book.description;if(book.cover){dialogCover.hidden=false;dialogCover.src=book.cover;dialogCover.alt=`Capa de ${book.title}`}else{dialogCover.hidden=true;dialogCover.removeAttribute("src")}readerName.value=sessionStorage.getItem("clubReaderName")||"";secretMode.checked=false;readerHint.textContent="A leitura normal abre as páginas do livro.";readButton.textContent="Abrir";if(typeof dialog.showModal==="function")dialog.showModal();else dialog.setAttribute("open","")}
function goToBook(){const name=readerName.value.trim();if(!name){readerName.focus();readerHint.textContent="Digite seu nome para continuar.";return}sessionStorage.setItem("clubReaderName",name);const target=secretMode.checked?`secret.html?book=${activeBookId}`:`reader.html?book=${activeBookId}`;window.location.href=target}
readButton.addEventListener("click",goToBook);secretMode.addEventListener("change",()=>{readerHint.textContent=secretMode.checked?"Edição alternativa selecionada.":"A leitura normal abre as páginas do livro."});readerName.addEventListener("input",()=>{if(readerName.value.trim())readerHint.textContent=secretMode.checked?"Edição alternativa selecionada.":"A leitura normal abre as páginas do livro."});
dialogClose.addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{const r=dialog.getBoundingClientRect();const inside=e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;if(!inside)dialog.close()});searchInput.addEventListener("input",()=>{const q=searchInput.value.trim().toLocaleLowerCase("pt-BR");renderBooks(books.filter(book=>`${book.title} ${book.author}`.toLocaleLowerCase("pt-BR").includes(q)))});
function setTheme(mode){const dark=mode==="dark";document.body.classList.toggle("dark",dark);themeIcon.textContent=dark?"☀":"☾";themeLabel.textContent=dark?"Claro":"Noite";localStorage.setItem("club-theme",dark?"dark":"light")}themeToggle.addEventListener("click",()=>setTheme(document.body.classList.contains("dark")?"light":"dark"));setTheme(localStorage.getItem("club-theme")||(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"));renderBooks(books);
